---
all:
  hosts:
    pve01.sysnet.co.il:
    pve02.sysnet.co.il:
    pve03.sysnet.co.il:

    # Pi NUT - primary
    nut.sysnet.co.il:
      ansible_user: pi

  children:
    primary:
      hosts:
        nut.sysnet.co.il:
    clients:
      hosts:
        pve01.sysnet.co.il:
        pve02.sysnet.co.il:
        pve03.sysnet.co.il:
